definitions:
  forms.ReportRequestForm:
    properties:
      deviceInfo:
        example: 00:11:22:33:FF:EE
        type: string
      latitude:
        example: 37.5428147089301
        type: number
      longitude:
        example: 126.96631451849314
        type: number
    type: object
  forms.ReportResponse:
    properties:
      createdAt:
        type: string
      deviceInfo:
        example: 00:11:22:33:FF:EE
        type: string
      latitude:
        example: 37.5428147089301
        type: number
      longitude:
        example: 126.96631451849314
        type: number
      updatedAt:
        type: string
    type: object
  forms.UserRegistrationForm:
    properties:
      is_student:
        type: boolean
      nickname:
        example: mengmota
        type: string
      partner_phone_number:
        example: "01012341234"
        type: string
      password:
        description: password field
        example: the!@#$pas123
        type: string
      phone_number:
        description: username field
        example: "01043214321"
        type: string
    type: object
info:
  contact: {}
  title: ShoeGuard Main Backend API
  version: "1.0"
paths:
  /report:
    post:
      consumes:
      - application/json
      description: Report Request with given information
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/forms.ReportRequestForm'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/forms.ReportResponse'
      security:
      - BasicAuth: []
      summary: Report Request
  /users/register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/forms.UserRegistrationForm'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/forms.UserRegistrationForm'
      summary: Register an user with given information
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
